### ISSUE TITLE
Additional intersect functionality

### ISSUE THREAD

**Issue by andywicht** [demarcog/Clipper#6]
In the plugin version for QGIS 3 there is the possibility to preview the clip result and the intersection result.
The intersection result can also be really interesting in a digitizing workflow.

Would it be possible to combine the clipper function with the intersection preview function to create a new tool which first does the clip (erases the parts under the clipping polygon) and then inserts the intersection preview result as a new feature?

That would also lead to the consistency that both preview functions have an related non-preview function.

**Comment by demarcog** [comment]
Hello,
I agree that this feature would be an evolution for the plugin but as developer I can see two issues about implementing such a function:
1. let's say that it is possible to clip and save intersection polygons as a new feature in the same layer, what to do with the clipping feature as a mask ? It should be deleted prior inserting the intersection feature? if not so the result would be overlapping polygons in the layer?
2. Implementing this features requires a full time coding since it is a matter of writing a completely new function or to combine clip and intersect functions accordingly that is to say a new function anyway ... so patience and cooperation would really be of help.
If you are willing to help me testing, let me know in details how this new feature of the plugin as I asked you in point 1. and I'll gladly try to implement it and periodically I'll send testing version to you in private or create a new fork in github.
Giuseppe De Marco

**Comment by andywicht** [comment]
Hello,
thank you for the response.
1. Isn't it just possible to delete the clipping feature as a last step to the process? Indeed it should not be part of the result set in any way (-> overlap). 
2. I am willing to help as much as I can. I have some python experience but none whatsoever connected to QGIS plugin development.

In my opinion all necessary calculation steps are already available in your plugin.
1. the logic which defines a polygon as a clipping polygon. In that case the intersecting polygon
2. intersect the input with the intersecting polygon (already done for the preview, just don't write the result in a temp layer but store it in memory).
3. clip the input with the intersecting polygon (as the clipper function currently does) to remove the parts under the intersecting polygon.
4. remove the intersecting polygon
5. insert the intersection from memory into the source layer
6. (attribute handling I am almost inclined to say that at the start just insert with null attributes)

Just let me know what I can do to help!
Thanks  alot.

Andreas

**Comment by demarcog** [comment]
Hello, sorry for my long time of silence ... I've been really busy at school and only today I've found some coding inspiration for implementing all the steps you suggested in a new function called self.clip_paste, I've also managed to design a new icon and a new Menu item for that. It definitely needs some testing and I would appreciate your contribution with that.
Please remember that at the present time there are 2 things to keep in mind:
1) Clipping has been made recalling the self.clip function but I think it should be rewritten inside or outside the self.clip_paste function to preserve the user possibility to not save the clipping
2) The new version of the plugin is hosted in a new branch where there is also an experimental function to clip with multiple selection I was working at and it needs to be tested either.

Let me know what to do you think about it

Bye for now
Giuseppe

**Comment by demarcog** [comment]
To be precise try and clone or download master3.2 branch for testing purposes

by 
Giuseppe

**Comment by andywicht** [comment]
Hi! Nice to hear that you had the time to fiddle with this issue. I am currently on holiday, so I will start testing as soon as I am back home! 
 
Andreas

**Comment by demarcog** [comment]
OK, have a nice time and when you go back to work let me know about the
testing then.

Giuseppe De Marco

**Comment by andywicht** [comment]
Hi Guiseppe,

I finally had some time to play around a little with the development version.
2 things came up:

1.  The result of the clipping action is not topologically clean
![clip_1](https://user-images.githubusercontent.com/21099522/43828642-62eba444-9afd-11e8-9284-0d1e746547f1.png)*2 overlapping polygons*

![clip_2](https://user-images.githubusercontent.com/21099522/43828643-6306c922-9afd-11e8-8fe8-a0e3094fbe84.png)*missing vertices*


2.  When using the new "Insert Intersection" function. I often get the error message `Select at least one feature !` I can not reproduce this error message.
(just to confirm that I use it right: first I select one of the two polygons, then click preview intersection, then click insert intersection)
When I successfully insert the intersection, I need to clip both polygons with the inserted intersection to avoid overlaps. When doing that the following happens:

> ![intersect_1](https://user-images.githubusercontent.com/21099522/43829093-6daeaa4c-9afe-11e8-84cb-7a86a7ee0aca.png) *shows the intersection*

> ![intersect_2](https://user-images.githubusercontent.com/21099522/43829094-6dc886e2-9afe-11e8-8276-4640e246f6f6.png) *clipping result after inserting and clipping*

**Here the lower polygon is duplicated!**

> ![intersect_3](https://user-images.githubusercontent.com/21099522/43829095-6ddf9580-9afe-11e8-919b-5562c6c2e0b8.png) *error in upper polygon*

**Here the clipping produces an edge probably due to rounding issues**

**Comment by demarcog** [comment]
I just uploaded the correct latest files, since I discovered that for some reasons in github resources_rc and other files weren't the latest. I found that out when I tried to reproduce these errors on Windows ...
I'll try some more and I'll try to reproduce these issues

**Comment by demarcog** [comment]
This morning I managed to have some good outcome from clip_paste() function under linux only though, because debugging on windows is really painful despite the very useful First Aid plugin, which is lacking variables inspection for now. I uploaded the new clipper.py file according to a real change in the new function you proposed. Now I will try to make it work on windows ... some screenshots from linux environment and unfortuanately there are some topological issues we have to investigate further: 
![screenshot from 2018-08-09 12-01-01](https://user-images.githubusercontent.com/5133491/43892638-c15eca18-9bcc-11e8-9e79-bb123cbd16c6.png)
![screenshot from 2018-08-09 12-01-20](https://user-images.githubusercontent.com/5133491/43892639-c17e6b34-9bcc-11e8-82f2-ffb94cc8385b.png)
![screenshot from 2018-08-09 12-01-38](https://user-images.githubusercontent.com/5133491/43892640-c199ad90-9bcc-11e8-8080-d9ade18db76d.png)
![screenshot from 2018-08-09 12-02-17](https://user-images.githubusercontent.com/5133491/43892641-c1b8d9c2-9bcc-11e8-8b36-5773472932af.png)
![screenshot from 2018-08-09 12-03-02](https://user-images.githubusercontent.com/5133491/43892642-c1d899c4-9bcc-11e8-872f-fe68872b062e.png)
![screenshot from 2018-08-09 12-03-41](https://user-images.githubusercontent.com/5133491/43892643-c1fd363a-9bcc-11e8-8eca-040ac4a9616d.png)
![screenshot from 2018-08-09 12-05-25](https://user-images.githubusercontent.com/5133491/43892644-c219c1f6-9bcc-11e8-92a9-53dbc5c6faa7.png)

**Comment by demarcog** [comment]
To use paste intersection after selecting a feature you can directly press the paste Button without necessarily perform an intersection preview.

**Comment by demarcog** [comment]
resolved !!!!! unbelievable !!! I just uploaded a new version of clipper.py with the clip a nd paste function fully functional
![Screenshot from 2019-07-22 11-40-16](https://user-images.githubusercontent.com/5133491/61637297-8c931780-ac97-11e9-93e9-f2206cf4b77d.png)
![Screenshot from 2019-07-22 11-40-52](https://user-images.githubusercontent.com/5133491/61637307-8ef57180-ac97-11e9-889e-796282c16178.png)
Try and test it please !!!
